### ISSUE TITLE
Add function to easily add Import-Module PSProfile to your $profile

### ISSUE THREAD

**Issue by scrthq** [scrthq/PSProfile#15]
```yaml
Name: Add-PSProfileToProfile
Synopsis: Adds 'Import-Module PSProfile -ArgumentList $ArgumentList' to the desired $profile file
Parameters:
  - Scope:
    - CurrentUserCurrentHost (default)
    - CurrentUserAllHosts
    - AllUsersCurrentHost
    - CurrentUserAllHosts
  - DisableLoadTimeMessage
```
